services:
  - type: web
    name: link-clicker-backend
    runtime: python
    buildCommand: ./build.sh
    startCommand: python app.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "false"
      - key: PORT
        value: 5000
