services:
  - type: web
    name: link-clicker-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python app.py
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0
      - key: PORT
        value: 5000

